version: 2
updates:
  - package-ecosystem: "python"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "pytest"
        versions: [">=5.0.0"]
