import random

facts = [
    "venus rotates on its axis so slowly that its day is longer than its year",
    "there are more trees on Earth than stars in the Milky Way galaxy",
    "the world's oldest piece of chewing gum is over 5,000 years old",
    "the universe is thought to be about 13.8 billion years old",
    "the tongue of a blue whale weighs as much as an elephant",
    "the tongue is the only muscle in the human body that is attached at only one end",
    "the speed of a computer mouse is measured in 'Mickeys.'",
    "the Sahara Desert used to be a lush, green area as recently as 6,000 years ago",
    "the Pistol Shrimp can create a sound loud enough to break glass",
    "the pistol shrimp can create a bubble hot enough to rival the sun's surface temperature",
    "the Milky Way galaxy is estimated to be 100,000 light-years in diameter",
    "the mantis shrimp can throw a punch at the speed of a bullet",
    "the largest known living organism is an aspen grove named Pando, located in Utah",
    "the human eye can distinguish about 10 million different colors",
    "the human brain can read up to 1,000 words per minute",
    "the human body has enough iron to make a 3-inch nail",
    "the highest temperature ever recorded on Earth was 56.7°C (134°F) in Death Valley, California",
    "the heart of a shrimp is located in its head",
    "the Great Barrier Reef is the largest living structure on Earth and can be seen from space",
    "the Eiffel Tower can be 15 cm taller during the summer due to the expansion of the metal",
    "the deepest part of the ocean is the Mariana Trench, which is deeper than Mount Everest is tall",
    'the Basenji dog breed is known as the "barkless dog" due to its unique larynx',
    "the average person walks the equivalent of five times around the world in their lifetime",
    "the average lifespan of a taste bud is 10 days",
    "the Andromeda Galaxy is on a collision course with the Milky Way, expected to occur in about 4 billion years",
    "the Amazon Rainforest produces 20 percent of the world's oxygen",
    "the age of the universe is determined through measurements of the cosmic microwave background radiation",
    "some turtles can breathe through their butts",
    "some frogs can freeze without dying and then thaw and continue living",
    "some bamboo plants can grow up to 91 cm (3 feet) in a single day",
    "saturn's density is low enough that the planet would float in water",
    "octopuses have three hearts and blue blood",
    "more than 1,200 different species of bats exist worldwide",
    "honeybees can flap their wings 200 times per second",
    "crows are known to hold grudges against specific individuals",
    "cats have over 100 vocal sounds, while dogs only have about 10",
    "bees can recognize human faces",
    "antarctica has an underground lake that stays liquid below the icy surface due to extreme saltiness",
    "an octopus can taste with its arms",
    "a sneeze can exceed speeds of 100 mph",
    "a single lightning strike can power a 100-watt bulb for over three months",
    "a single cloud can weigh more than 1 million pounds",
    "a Rubik's Cube has 43 quintillion possible configurations",
    "a group of owls is called a 'parliament.'",
    "a group of kangaroos is called a 'mob.'",
    "a group of jellyfish is called a 'smack.'",
    "a group of frogs is called an 'army.'",
    "a group of cats is called a 'clowder.'",
    "a day on Mercury lasts approximately as long as 59 days on Earth",
    "a bolt of lightning contains enough energy to toast 100,000 slices of bread",
    "a group of hedgehogs is known as an 'array.'",
    "lake Baikal in Siberia contains more water than all the North American Great Lakes combined",
    "the sun's core is so hot that a grain of sand there would shine like 100 million candles",
    "there are more possible iterations of a game of chess than there are atoms in the known universe",
    "the Amazon River once flowed in the opposite direction, from east to west",
    "the human body is capable of producing aspirin",
    "a group of ravens is called an 'unkindness' or 'conspiracy.'",
    "starfish can re-grow their arms. In some cases, a new starfish can grow from a severed arm",
    "the average cumulus cloud weighs about 1.1 million pounds",
    "the lifespan of a single red blood cell is about 120 days",
    "a group of unicorns is called a 'blessing.'",
    "the world's largest desert is not the Sahara, but Antarctica",
    "the longest time between two twins being born is 87 days",
    "the shortest war in history was between Britain and Zanzibar on August 27, 1896. Zanzibar surrendered after 38 minutes",
    "a jiffy is an actual unit of time for 1/100th of a second",
    "the universe is thought to be flat",
    "a group of pandas is called an 'embarrassment'",
    "the heart of a shrimp is located in its head",
    "an adult human has 206 bones, while a baby is born with approximately 270",
    "the Apollo 11 computer had less processing power than a modern-day cellphone",
    "a group of ladybugs is called a 'loveliness.'",
    "the smallest bone in the human body is the stapes bone in the ear",
    "the longest word in the English language without a vowel is 'rhythms.'",
    "a lion's roar can be heard from 5 miles away",
    "a group of porcupines is called a 'prickle.'",
    "butterflies taste with their feet",
    "the strongest muscle in the human body is the masseter (jaw muscle)",
    "a group of owls is called a 'parliament.'",
    "the moon moves away from Earth at a rate of about 1.5 inches per year",
    "a human sneeze can travel about 100 miles per hour",
    "a group of kangaroos is called a 'mob.'",
    "the total length of the human nervous system is about 600 miles",
    "a group of butterflies is called a 'flutter.'",
    "the Atlantic Ocean is saltier than the Pacific Ocean",
    "a group of crows is called a 'murder.'",
    "the human eye can distinguish up to 10 million different colors",
    "a group of larks is called an 'exaltation'",
    "the human skeleton is renewed every 10 years",
    "a group of ferrets is called a 'business.'",
    "the average human walks the equivalent of three times around the world in a lifetime",
    "a group of frogs is called an 'army'",
    "a crocodile cannot stick its tongue out",
    "a group of rhinos is called a 'crash.'",
    "hot water will turn into ice faster than cold water",
    "a group of giraffes is called a 'tower.'",
    "the strongest natural material in the world is spider silk",
    "a group of zebras is called a 'dazzle.'",
    "the shortest complete sentence in the English language is 'Go.'",
    "a group of goats is called a 'trip.'",
    "the world's largest amphibian is the Chinese giant salamander, which can grow up to 6 feet in length.",
]


def return_random():
    return random.choice(facts)
