import random

facts = [
    "The average person spends 6 months of their life waiting for a red light to turn green.",
    "a bolt of lightning can reach temperatures of up to 30,000 degrees Celsius, which is 5 times hotter than the surface of the sun!",
    "a caterpillar has more muscles than a human.",
    "a cockroach can survive for up to a week without its head.",
    "a full moon is nine times brighter than a half moon.",
    "a group of flamingos is called a \"flamboyance\".",
    "a hummingbird's heart beats 1,260 times per minute!",
    "a jumbo jet weighs about as much as 50 elephants.",
    "a lightning bolt can heat the air around it to over 30,000 degrees Celsius!",
    "a single drop of seawater contains millions of tiny organisms, including tiny plants and animals.",
    "a single sneeze can travel at a speed of up to 100 miles per hour.",
    "a single teaspoon of a neutron star would weigh about 6 billion tons!",
    "a snail can sleep for up to 3 years.",
    "bananas are technically berries, while strawberries are not.",
    "camels have three eyelids to protect their eyes from sand.",
    "cows have best friends and can become stressed when separated from them.",
    "dolphins sleep with one eye open.",
    "earthworms have five hearts.",
    "frogs can breathe through their skin.",
    "honey never spoils and can last indefinitely.",
    "humans share about 60% of their DNA with bananas.",
    "it takes about 8 minutes for sunlight to travel from the sun to Earth.",
    "jellyfish are made up of about 95% water.",
    "kangaroos can't walk backward.",
    "male mosquitoes don't bite; only female mosquitoes do.",
    "ostriches have the largest eyes of any land animal.",
    "polar bears have black skin to better absorb the sun's warmth.",
    "sharks have been around for over 400 million years, which is longer than trees.",
    "slugs have four noses.",
    "a cop once fucked my sister."
    "some plants can \"hear\" when they are being eaten and respond defensively.",
    "spiders are not insects; they belong to the arachnid family.",
    "the average person produces enough saliva in their lifetime to fill two swimming pools.",
    "the average person will shed about 40 pounds of skin in their lifetime.",
    "the average person will spend six months of their life waiting for red lights to turn green!",
    "the biggest snowflake ever recorded was 15 inches in diameter and 8 inches thick!",
    "the Earth is the only planet in our solar system that has liquid water on its surface.",
    "the Earth rotates on its axis once every 24 hours, which is why we have day and night.",
    "the Earth's atmosphere is made up of 78% nitrogen, 21% oxygen, and 1% other gases.",
    "the Eiffel Tower grows about six inches taller during the summer due to thermal expansion.",
    "the heart of a blue whale is so big, a human could swim through its arteries!",
    "the human body contains enough carbon to make about 9,000 pencils.",
    "the human nose can detect over 1 trillion different scents.",
    "the largest dinosaur ever discovered was over 100 feet long and weighed over 100 tons.",
    "the largest living organism on earth is a fungus called Armillaria ostoyae, which covers over 2,200 acres in Oregon.",
    "the loudest animal on Earth is the sperm whale, whose clicks can reach 230 decibels.",
    "the moon is about 1/4th the size of Earth.",
    "the only mammals capable of true flight are bats.",
    "the shortest war in history lasted only 38 minutes, between Britain and Zanzibar in 1896.",
    "the sun is so big that it contains 99.86% of all the matter in our solar system.",
    "the tallest mammal in the world is the giraffe, which can grow up to 18 feet tall!",
    "the tongue has different taste receptors for sweet, sour, salty, and bitter.",
    "the tongue of a blue whale is so big, 50 people could stand on it.",
    "there are approximately 100 billion stars in our Milky Way galaxy.",
    "there are more bacteria cells in your body than human cells.",
    "venus is the hottest planet in our solar system, even though it's not the closest to the sun.",
    "your bones are composed of 31% water.",
    "your left lung is smaller than your right lung to make room for your heart."
]

def return_random():
    return random.choice(facts)