"""empty message

Revision ID: 550dfbf40243
Revises: d550cf09a12f
Create Date: 2023-04-01 02:57:34.230520

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '550dfbf40243'
down_revision = 'd550cf09a12f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('o_auth_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=255), nullable=False),
    sa.Column('refresh_token', sa.String(length=255), nullable=False),
    sa.Column('expires_in', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['oauth_client.client_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token'),
    sa.UniqueConstraint('refresh_token')
    )
    with op.batch_alter_table('oauth_token', schema=None) as batch_op:
        batch_op.drop_index('access_token')
        batch_op.drop_index('refresh_token')

    op.drop_table('oauth_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_token',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('access_token', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('refresh_token', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('expires_in', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('client_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('scopes', mysql.TEXT(), nullable=True),
    sa.Column('issued_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['oauth_client.client_id'], name='oauth_token_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='oauth_token_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('oauth_token', schema=None) as batch_op:
        batch_op.create_index('refresh_token', ['refresh_token'], unique=False)
        batch_op.create_index('access_token', ['access_token'], unique=False)

    op.drop_table('o_auth_token')
    # ### end Alembic commands ###
